sudo: required
language: python
python:
  - "3.7-dev"
  - "3.6"

cache: pip

matrix:
  include:
    - addons:
        mariadb: 5.5
      python: "3.6"

    - addons:
        mariadb: 10.1
      python: "pypy"

    - python: 3.6
      env: CHECK_DOCS=1

# not done: no extensive reformatting of Upstream, please
#    - python: 3.6
#      env: CHECK_FORMATTING=1

# different py version from 5.6 and 5.7 as cache seems to be based on py version
# http://dev.mysql.com/downloads/mysql/5.7.html has latest development release version
# really only need libaio1 for DB builds however libaio-dev is whitelisted for container builds and liaio1 isn't
install:
    - export PASSWORD=travis;
    - pip install -U coveralls pytest pytest-trio coverage

before_script:
    - ./.travis/initializedb.sh
    - mysql -e 'create database test_trio_mysql  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
    - mysql -e 'create database test_trio_mysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
    - mysql -u root -e "create user travis_pass identified by 'some password'; grant all on test_trio_mysql2.* to travis;"
    - mysql -u root -e "create user travis_pass@localhost identified by 'some password'; grant all on test_trio_mysql2.* to travis@localhost;"
    - mysql -u travis_pass -p 'some password' -e 'show databases'
    - mysql -e 'select VERSION()'
    - python -VV
    - rm -f ~/.my.cnf # set in .travis.initialize.db.sh for the above commands - we should be using database.json however
    - export COVERALLS_PARALLEL=true

script:
  - .travis/run.sh

after_success:
    - coveralls
    - cat /tmp/mysql.err

after_failure:
    - cat /tmp/mysql.err

# vim: sw=2 ts=2 sts=2 expandtab
